baseURL = "https://www.cookintrix.it"
languageCode = "it-it"
defaultContentLanguage = "it"
defaultContentLanguageInSubdir = true
title = "Cookintrix"
enableEmoji = true

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        respectDoNoTrack = true
        useSessionStorage = true
    [privacy.youtube]
        privacyEnhanced = true
    [privacy.vimeo]
        enableDMT = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "gruvbox"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.it]
    languageName = "Italian"
    languagedirection = "it"
    weight = 1
    [languages.it.params]
      headerTitle = "Blog di Cookintrix"
      motto = "L'ingrediente più importante è il cuore"
  [languages.en]
    languageName = "English"
    languagedirection = "en"
    weight = 2
    [languages.en.params]
      motto = "Most fundamental ingredient is the heart"

[params]
  background = "#f7f7f7"
  backgroundImage = "/img/back.jpg"
  linkColor = "seagreen"

  # dark mode
  defaultDark = true
  backgroundDark = "#282828"
  backgroundImageDark = "/img/back.jpg"
  darkLinkColor = "darkseagreen"
  # darkNav = true
  dark404 = true

  author = "Cookintrix"
  # description = ""
  avatar = "/img/avatar.png"
  # headerTitle = ""
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  footerBottomText = ""

  rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "giulia_rossi1996@libero.it"
  # twitter = ""
  # facebook = ""
  instagram = "cookintrix"
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2021

  favicon = "/img/avatar.png"

  highlightjs = true
  highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # search engine
  enableRobotsTXT = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true

  [params.advanced]
    customCSS = ["css/custom.css"]
    # customJS = []
